### ISSUE TITLE
GitHub sync does not always sync all files.

### ISSUE THREAD

**Issue by GronbergInfo** [vanilla/github-sync#1]
I have quite often noticed that when i commit my stuff at my work laptop to the "localrepo" and then sync it to github from vs.net 2013 community edition, all files is not always synced at all.
Like yesterday, i was missing "frmFiles.cs" even when i have commited/synced that form-files several times during the day.
When i check the repo at GitHub, its missing from there too.
And this is not the first time this doesnt work..

How i commit/sync:
1) I save all files
2) I change to "Team Explorer" tab.
3) I click on the "Changed button"
4) I fill in the commit message
5) I click  "Commit"
6) I get the message like: "Commit 8f81d36b created locally. Sync to share your changes with the server."
7) I click on the "Sync" in the yellow information textbox
8) I click the "Sync"-button
9) i wait for the "Successfully synchronized incoming and outgoing commits."

Thats it. In this manner, i expect all files to get commited and synced, and yet it does not always do that. Today when i got back to work, frmFiles.cs was marked as unsynced, even when i synced before i went home.

**Comment by tburry** [comment]
I think you've got the wrong repo here.
